name: Java CI

on:
  workflow_dispatch: 
  push:
    branches:
      - "*"


jobs:
  build:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: echo "nathan" | python main.py 
                  
     
