name: Python CI

on:
  workflow_dispatch: 
  push:
    branches:
      - "*"


jobs:
  checking:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0
      - run:   chmod +x input_script.exp
      - run:   ./input_script.exp
                  
     
